language: node_js
node_js:
  - "9"
  - "10"
cache:
  directories:
    - "node_modules"
addons:
  code_climate:
    repo_token:

before_install:
  - npm i -g npm@latest
install:
  - npm install
script:
  - npm test
after_script:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info